package Modelos;
// Generated Feb 28, 2019 11:49:11 AM by Hibernate Tools 4.3.1

import java.util.Set;
import javax.validation.ConstraintViolation;
import javax.validation.Validator;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
//import javax.validation.executable.ExecutableValidator;
import javax.validation.metadata.BeanDescriptor;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.Range;






/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable{



   
     private Integer id;
  
     private String nombre;
 
     private String apellidos;

     private int edad;
  
     private String direccion;
       
     private String dni;

     private int cp;
       

     private int telefono;

     private String correo;
     private String cadenaBusqueda;
    public Clientes() {
    }

    public Clientes(String nombre, String apellidos, int edad, String direccion, String dni, int cp, int telefono, String correo) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.direccion = direccion;
       this.dni = dni;
       this.cp = cp;
       this.telefono = telefono;
       this.correo = correo;
    }

    public void setCadenaBusqueda(String cadenaBusqueda) {
        this.cadenaBusqueda = cadenaBusqueda;
    }

    public String getCadenaBusqueda() {
        return cadenaBusqueda;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getCp() {
        
        return this.cp;
   
        
    }
    
    public void setCp(int cp) {
 
        this.cp = cp;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

 


}


